#! /bin/sh

sxhkd &
~/.config/bspwm/statusbar &

bspc config border_width        2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor HDMI-0 	I II
bspc monitor DVI-0	III IV

#~/.config/bspwm/autostart.sh &
